# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/leaf/Projects/Sunshine/JuniorsToolbox

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/leaf/Projects/Sunshine/JuniorsToolbox

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leaf/Projects/Sunshine/JuniorsToolbox/CMakeFiles /home/leaf/Projects/Sunshine/JuniorsToolbox//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/leaf/Projects/Sunshine/JuniorsToolbox/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named JuniorsToolbox

# Build rule for target.
JuniorsToolbox: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 JuniorsToolbox
.PHONY : JuniorsToolbox

# fast build rule for target.
JuniorsToolbox/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/build
.PHONY : JuniorsToolbox/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named j3dultra

# Build rule for target.
j3dultra: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 j3dultra
.PHONY : j3dultra

# fast build rule for target.
j3dultra/fast:
	$(MAKE) $(MAKESILENT) -f lib/J3DUltra/CMakeFiles/j3dultra.dir/build.make lib/J3DUltra/CMakeFiles/j3dultra.dir/build
.PHONY : j3dultra/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f lib/J3DUltra/lib/glm/CMakeFiles/uninstall.dir/build.make lib/J3DUltra/lib/glm/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named libflipper

# Build rule for target.
libflipper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 libflipper
.PHONY : libflipper

# fast build rule for target.
libflipper/fast:
	$(MAKE) $(MAKESILENT) -f lib/J3DUltra/lib/libflipper/CMakeFiles/libflipper.dir/build.make lib/J3DUltra/lib/libflipper/CMakeFiles/libflipper.dir/build
.PHONY : libflipper/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/glfw.dir/build.make lib/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/src/CMakeFiles/update_mappings.dir/build.make lib/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) $(MAKESILENT) -f lib/glfw/docs/CMakeFiles/docs.dir/build.make lib/glfw/docs/CMakeFiles/docs.dir/build
.PHONY : docs/fast

lib/ImGuiFileDialog/ImGuiFileDialog.o: lib/ImGuiFileDialog/ImGuiFileDialog.cpp.o
.PHONY : lib/ImGuiFileDialog/ImGuiFileDialog.o

# target to build an object file
lib/ImGuiFileDialog/ImGuiFileDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/lib/ImGuiFileDialog/ImGuiFileDialog.cpp.o
.PHONY : lib/ImGuiFileDialog/ImGuiFileDialog.cpp.o

lib/ImGuiFileDialog/ImGuiFileDialog.i: lib/ImGuiFileDialog/ImGuiFileDialog.cpp.i
.PHONY : lib/ImGuiFileDialog/ImGuiFileDialog.i

# target to preprocess a source file
lib/ImGuiFileDialog/ImGuiFileDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/lib/ImGuiFileDialog/ImGuiFileDialog.cpp.i
.PHONY : lib/ImGuiFileDialog/ImGuiFileDialog.cpp.i

lib/ImGuiFileDialog/ImGuiFileDialog.s: lib/ImGuiFileDialog/ImGuiFileDialog.cpp.s
.PHONY : lib/ImGuiFileDialog/ImGuiFileDialog.s

# target to generate assembly for a file
lib/ImGuiFileDialog/ImGuiFileDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/lib/ImGuiFileDialog/ImGuiFileDialog.cpp.s
.PHONY : lib/ImGuiFileDialog/ImGuiFileDialog.cpp.s

lib/imgui/backends/imgui_impl_glfw.o: lib/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : lib/imgui/backends/imgui_impl_glfw.o

# target to build an object file
lib/imgui/backends/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/backends/imgui_impl_glfw.cpp.o
.PHONY : lib/imgui/backends/imgui_impl_glfw.cpp.o

lib/imgui/backends/imgui_impl_glfw.i: lib/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
lib/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_glfw.cpp.i

lib/imgui/backends/imgui_impl_glfw.s: lib/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
lib/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_glfw.cpp.s

lib/imgui/backends/imgui_impl_opengl3.o: lib/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : lib/imgui/backends/imgui_impl_opengl3.o

# target to build an object file
lib/imgui/backends/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/backends/imgui_impl_opengl3.cpp.o
.PHONY : lib/imgui/backends/imgui_impl_opengl3.cpp.o

lib/imgui/backends/imgui_impl_opengl3.i: lib/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
lib/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : lib/imgui/backends/imgui_impl_opengl3.cpp.i

lib/imgui/backends/imgui_impl_opengl3.s: lib/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
lib/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : lib/imgui/backends/imgui_impl_opengl3.cpp.s

lib/imgui/imgui.o: lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.o

# target to build an object file
lib/imgui/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui.cpp.o
.PHONY : lib/imgui/imgui.cpp.o

lib/imgui/imgui.i: lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.i

# target to preprocess a source file
lib/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui.cpp.i
.PHONY : lib/imgui/imgui.cpp.i

lib/imgui/imgui.s: lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.s

# target to generate assembly for a file
lib/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui.cpp.s
.PHONY : lib/imgui/imgui.cpp.s

lib/imgui/imgui_demo.o: lib/imgui/imgui_demo.cpp.o
.PHONY : lib/imgui/imgui_demo.o

# target to build an object file
lib/imgui/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_demo.cpp.o
.PHONY : lib/imgui/imgui_demo.cpp.o

lib/imgui/imgui_demo.i: lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.i

# target to preprocess a source file
lib/imgui/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_demo.cpp.i
.PHONY : lib/imgui/imgui_demo.cpp.i

lib/imgui/imgui_demo.s: lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.s

# target to generate assembly for a file
lib/imgui/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_demo.cpp.s
.PHONY : lib/imgui/imgui_demo.cpp.s

lib/imgui/imgui_draw.o: lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.o

# target to build an object file
lib/imgui/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_draw.cpp.o
.PHONY : lib/imgui/imgui_draw.cpp.o

lib/imgui/imgui_draw.i: lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.i

# target to preprocess a source file
lib/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_draw.cpp.i
.PHONY : lib/imgui/imgui_draw.cpp.i

lib/imgui/imgui_draw.s: lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.s

# target to generate assembly for a file
lib/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_draw.cpp.s
.PHONY : lib/imgui/imgui_draw.cpp.s

lib/imgui/imgui_tables.o: lib/imgui/imgui_tables.cpp.o
.PHONY : lib/imgui/imgui_tables.o

# target to build an object file
lib/imgui/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_tables.cpp.o
.PHONY : lib/imgui/imgui_tables.cpp.o

lib/imgui/imgui_tables.i: lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.i

# target to preprocess a source file
lib/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_tables.cpp.i
.PHONY : lib/imgui/imgui_tables.cpp.i

lib/imgui/imgui_tables.s: lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.s

# target to generate assembly for a file
lib/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_tables.cpp.s
.PHONY : lib/imgui/imgui_tables.cpp.s

lib/imgui/imgui_widgets.o: lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.o

# target to build an object file
lib/imgui/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_widgets.cpp.o
.PHONY : lib/imgui/imgui_widgets.cpp.o

lib/imgui/imgui_widgets.i: lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.i

# target to preprocess a source file
lib/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_widgets.cpp.i
.PHONY : lib/imgui/imgui_widgets.cpp.i

lib/imgui/imgui_widgets.s: lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.s

# target to generate assembly for a file
lib/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/imgui.dir/build.make CMakeFiles/imgui.dir/lib/imgui/imgui_widgets.cpp.s
.PHONY : lib/imgui/imgui_widgets.cpp.s

src/bmg/bmg.o: src/bmg/bmg.cpp.o
.PHONY : src/bmg/bmg.o

# target to build an object file
src/bmg/bmg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/bmg/bmg.cpp.o
.PHONY : src/bmg/bmg.cpp.o

src/bmg/bmg.i: src/bmg/bmg.cpp.i
.PHONY : src/bmg/bmg.i

# target to preprocess a source file
src/bmg/bmg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/bmg/bmg.cpp.i
.PHONY : src/bmg/bmg.cpp.i

src/bmg/bmg.s: src/bmg/bmg.cpp.s
.PHONY : src/bmg/bmg.s

# target to generate assembly for a file
src/bmg/bmg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/bmg/bmg.cpp.s
.PHONY : src/bmg/bmg.cpp.s

src/gui/application.o: src/gui/application.cpp.o
.PHONY : src/gui/application.o

# target to build an object file
src/gui/application.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/application.cpp.o
.PHONY : src/gui/application.cpp.o

src/gui/application.i: src/gui/application.cpp.i
.PHONY : src/gui/application.i

# target to preprocess a source file
src/gui/application.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/application.cpp.i
.PHONY : src/gui/application.cpp.i

src/gui/application.s: src/gui/application.cpp.s
.PHONY : src/gui/application.s

# target to generate assembly for a file
src/gui/application.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/application.cpp.s
.PHONY : src/gui/application.cpp.s

src/gui/camera.o: src/gui/camera.cpp.o
.PHONY : src/gui/camera.o

# target to build an object file
src/gui/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/camera.cpp.o
.PHONY : src/gui/camera.cpp.o

src/gui/camera.i: src/gui/camera.cpp.i
.PHONY : src/gui/camera.i

# target to preprocess a source file
src/gui/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/camera.cpp.i
.PHONY : src/gui/camera.cpp.i

src/gui/camera.s: src/gui/camera.cpp.s
.PHONY : src/gui/camera.s

# target to generate assembly for a file
src/gui/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/camera.cpp.s
.PHONY : src/gui/camera.cpp.s

src/gui/context.o: src/gui/context.cpp.o
.PHONY : src/gui/context.o

# target to build an object file
src/gui/context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/context.cpp.o
.PHONY : src/gui/context.cpp.o

src/gui/context.i: src/gui/context.cpp.i
.PHONY : src/gui/context.i

# target to preprocess a source file
src/gui/context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/context.cpp.i
.PHONY : src/gui/context.cpp.i

src/gui/context.s: src/gui/context.cpp.s
.PHONY : src/gui/context.s

# target to generate assembly for a file
src/gui/context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/context.cpp.s
.PHONY : src/gui/context.cpp.s

src/gui/input.o: src/gui/input.cpp.o
.PHONY : src/gui/input.o

# target to build an object file
src/gui/input.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/input.cpp.o
.PHONY : src/gui/input.cpp.o

src/gui/input.i: src/gui/input.cpp.i
.PHONY : src/gui/input.i

# target to preprocess a source file
src/gui/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/input.cpp.i
.PHONY : src/gui/input.cpp.i

src/gui/input.s: src/gui/input.cpp.s
.PHONY : src/gui/input.s

# target to generate assembly for a file
src/gui/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/input.cpp.s
.PHONY : src/gui/input.cpp.s

src/gui/util.o: src/gui/util.cpp.o
.PHONY : src/gui/util.o

# target to build an object file
src/gui/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/util.cpp.o
.PHONY : src/gui/util.cpp.o

src/gui/util.i: src/gui/util.cpp.i
.PHONY : src/gui/util.i

# target to preprocess a source file
src/gui/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/util.cpp.i
.PHONY : src/gui/util.cpp.i

src/gui/util.s: src/gui/util.cpp.s
.PHONY : src/gui/util.s

# target to generate assembly for a file
src/gui/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/gui/util.cpp.s
.PHONY : src/gui/util.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/objlib/meta/enum.o: src/objlib/meta/enum.cpp.o
.PHONY : src/objlib/meta/enum.o

# target to build an object file
src/objlib/meta/enum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/enum.cpp.o
.PHONY : src/objlib/meta/enum.cpp.o

src/objlib/meta/enum.i: src/objlib/meta/enum.cpp.i
.PHONY : src/objlib/meta/enum.i

# target to preprocess a source file
src/objlib/meta/enum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/enum.cpp.i
.PHONY : src/objlib/meta/enum.cpp.i

src/objlib/meta/enum.s: src/objlib/meta/enum.cpp.s
.PHONY : src/objlib/meta/enum.s

# target to generate assembly for a file
src/objlib/meta/enum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/enum.cpp.s
.PHONY : src/objlib/meta/enum.cpp.s

src/objlib/meta/member.o: src/objlib/meta/member.cpp.o
.PHONY : src/objlib/meta/member.o

# target to build an object file
src/objlib/meta/member.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/member.cpp.o
.PHONY : src/objlib/meta/member.cpp.o

src/objlib/meta/member.i: src/objlib/meta/member.cpp.i
.PHONY : src/objlib/meta/member.i

# target to preprocess a source file
src/objlib/meta/member.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/member.cpp.i
.PHONY : src/objlib/meta/member.cpp.i

src/objlib/meta/member.s: src/objlib/meta/member.cpp.s
.PHONY : src/objlib/meta/member.s

# target to generate assembly for a file
src/objlib/meta/member.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/member.cpp.s
.PHONY : src/objlib/meta/member.cpp.s

src/objlib/meta/struct.o: src/objlib/meta/struct.cpp.o
.PHONY : src/objlib/meta/struct.o

# target to build an object file
src/objlib/meta/struct.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/struct.cpp.o
.PHONY : src/objlib/meta/struct.cpp.o

src/objlib/meta/struct.i: src/objlib/meta/struct.cpp.i
.PHONY : src/objlib/meta/struct.i

# target to preprocess a source file
src/objlib/meta/struct.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/struct.cpp.i
.PHONY : src/objlib/meta/struct.cpp.i

src/objlib/meta/struct.s: src/objlib/meta/struct.cpp.s
.PHONY : src/objlib/meta/struct.s

# target to generate assembly for a file
src/objlib/meta/struct.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/struct.cpp.s
.PHONY : src/objlib/meta/struct.cpp.s

src/objlib/meta/value.o: src/objlib/meta/value.cpp.o
.PHONY : src/objlib/meta/value.o

# target to build an object file
src/objlib/meta/value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/value.cpp.o
.PHONY : src/objlib/meta/value.cpp.o

src/objlib/meta/value.i: src/objlib/meta/value.cpp.i
.PHONY : src/objlib/meta/value.i

# target to preprocess a source file
src/objlib/meta/value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/value.cpp.i
.PHONY : src/objlib/meta/value.cpp.i

src/objlib/meta/value.s: src/objlib/meta/value.cpp.s
.PHONY : src/objlib/meta/value.s

# target to generate assembly for a file
src/objlib/meta/value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/meta/value.cpp.s
.PHONY : src/objlib/meta/value.cpp.s

src/objlib/object.o: src/objlib/object.cpp.o
.PHONY : src/objlib/object.o

# target to build an object file
src/objlib/object.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/object.cpp.o
.PHONY : src/objlib/object.cpp.o

src/objlib/object.i: src/objlib/object.cpp.i
.PHONY : src/objlib/object.i

# target to preprocess a source file
src/objlib/object.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/object.cpp.i
.PHONY : src/objlib/object.cpp.i

src/objlib/object.s: src/objlib/object.cpp.s
.PHONY : src/objlib/object.s

# target to generate assembly for a file
src/objlib/object.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/object.cpp.s
.PHONY : src/objlib/object.cpp.s

src/objlib/template.o: src/objlib/template.cpp.o
.PHONY : src/objlib/template.o

# target to build an object file
src/objlib/template.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/template.cpp.o
.PHONY : src/objlib/template.cpp.o

src/objlib/template.i: src/objlib/template.cpp.i
.PHONY : src/objlib/template.i

# target to preprocess a source file
src/objlib/template.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/template.cpp.i
.PHONY : src/objlib/template.cpp.i

src/objlib/template.s: src/objlib/template.cpp.s
.PHONY : src/objlib/template.s

# target to generate assembly for a file
src/objlib/template.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/objlib/template.cpp.s
.PHONY : src/objlib/template.cpp.s

src/rail/node.o: src/rail/node.cpp.o
.PHONY : src/rail/node.o

# target to build an object file
src/rail/node.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/rail/node.cpp.o
.PHONY : src/rail/node.cpp.o

src/rail/node.i: src/rail/node.cpp.i
.PHONY : src/rail/node.i

# target to preprocess a source file
src/rail/node.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/rail/node.cpp.i
.PHONY : src/rail/node.cpp.i

src/rail/node.s: src/rail/node.cpp.s
.PHONY : src/rail/node.s

# target to generate assembly for a file
src/rail/node.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/rail/node.cpp.s
.PHONY : src/rail/node.cpp.s

src/rail/rail.o: src/rail/rail.cpp.o
.PHONY : src/rail/rail.o

# target to build an object file
src/rail/rail.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/rail/rail.cpp.o
.PHONY : src/rail/rail.cpp.o

src/rail/rail.i: src/rail/rail.cpp.i
.PHONY : src/rail/rail.i

# target to preprocess a source file
src/rail/rail.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/rail/rail.cpp.i
.PHONY : src/rail/rail.cpp.i

src/rail/rail.s: src/rail/rail.cpp.s
.PHONY : src/rail/rail.s

# target to generate assembly for a file
src/rail/rail.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/rail/rail.cpp.s
.PHONY : src/rail/rail.cpp.s

src/scene/raildata.o: src/scene/raildata.cpp.o
.PHONY : src/scene/raildata.o

# target to build an object file
src/scene/raildata.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/scene/raildata.cpp.o
.PHONY : src/scene/raildata.cpp.o

src/scene/raildata.i: src/scene/raildata.cpp.i
.PHONY : src/scene/raildata.i

# target to preprocess a source file
src/scene/raildata.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/scene/raildata.cpp.i
.PHONY : src/scene/raildata.cpp.i

src/scene/raildata.s: src/scene/raildata.cpp.s
.PHONY : src/scene/raildata.s

# target to generate assembly for a file
src/scene/raildata.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/scene/raildata.cpp.s
.PHONY : src/scene/raildata.cpp.s

src/scene/scene.o: src/scene/scene.cpp.o
.PHONY : src/scene/scene.o

# target to build an object file
src/scene/scene.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/scene/scene.cpp.o
.PHONY : src/scene/scene.cpp.o

src/scene/scene.i: src/scene/scene.cpp.i
.PHONY : src/scene/scene.i

# target to preprocess a source file
src/scene/scene.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/scene/scene.cpp.i
.PHONY : src/scene/scene.cpp.i

src/scene/scene.s: src/scene/scene.cpp.s
.PHONY : src/scene/scene.s

# target to generate assembly for a file
src/scene/scene.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/scene/scene.cpp.s
.PHONY : src/scene/scene.cpp.s

src/serial.o: src/serial.cpp.o
.PHONY : src/serial.o

# target to build an object file
src/serial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/serial.cpp.o
.PHONY : src/serial.cpp.o

src/serial.i: src/serial.cpp.i
.PHONY : src/serial.i

# target to preprocess a source file
src/serial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/serial.cpp.i
.PHONY : src/serial.cpp.i

src/serial.s: src/serial.cpp.s
.PHONY : src/serial.s

# target to generate assembly for a file
src/serial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/JuniorsToolbox.dir/build.make CMakeFiles/JuniorsToolbox.dir/src/serial.cpp.s
.PHONY : src/serial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... docs"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... JuniorsToolbox"
	@echo "... glfw"
	@echo "... imgui"
	@echo "... j3dultra"
	@echo "... libflipper"
	@echo "... lib/ImGuiFileDialog/ImGuiFileDialog.o"
	@echo "... lib/ImGuiFileDialog/ImGuiFileDialog.i"
	@echo "... lib/ImGuiFileDialog/ImGuiFileDialog.s"
	@echo "... lib/imgui/backends/imgui_impl_glfw.o"
	@echo "... lib/imgui/backends/imgui_impl_glfw.i"
	@echo "... lib/imgui/backends/imgui_impl_glfw.s"
	@echo "... lib/imgui/backends/imgui_impl_opengl3.o"
	@echo "... lib/imgui/backends/imgui_impl_opengl3.i"
	@echo "... lib/imgui/backends/imgui_impl_opengl3.s"
	@echo "... lib/imgui/imgui.o"
	@echo "... lib/imgui/imgui.i"
	@echo "... lib/imgui/imgui.s"
	@echo "... lib/imgui/imgui_demo.o"
	@echo "... lib/imgui/imgui_demo.i"
	@echo "... lib/imgui/imgui_demo.s"
	@echo "... lib/imgui/imgui_draw.o"
	@echo "... lib/imgui/imgui_draw.i"
	@echo "... lib/imgui/imgui_draw.s"
	@echo "... lib/imgui/imgui_tables.o"
	@echo "... lib/imgui/imgui_tables.i"
	@echo "... lib/imgui/imgui_tables.s"
	@echo "... lib/imgui/imgui_widgets.o"
	@echo "... lib/imgui/imgui_widgets.i"
	@echo "... lib/imgui/imgui_widgets.s"
	@echo "... src/bmg/bmg.o"
	@echo "... src/bmg/bmg.i"
	@echo "... src/bmg/bmg.s"
	@echo "... src/gui/application.o"
	@echo "... src/gui/application.i"
	@echo "... src/gui/application.s"
	@echo "... src/gui/camera.o"
	@echo "... src/gui/camera.i"
	@echo "... src/gui/camera.s"
	@echo "... src/gui/context.o"
	@echo "... src/gui/context.i"
	@echo "... src/gui/context.s"
	@echo "... src/gui/input.o"
	@echo "... src/gui/input.i"
	@echo "... src/gui/input.s"
	@echo "... src/gui/util.o"
	@echo "... src/gui/util.i"
	@echo "... src/gui/util.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/objlib/meta/enum.o"
	@echo "... src/objlib/meta/enum.i"
	@echo "... src/objlib/meta/enum.s"
	@echo "... src/objlib/meta/member.o"
	@echo "... src/objlib/meta/member.i"
	@echo "... src/objlib/meta/member.s"
	@echo "... src/objlib/meta/struct.o"
	@echo "... src/objlib/meta/struct.i"
	@echo "... src/objlib/meta/struct.s"
	@echo "... src/objlib/meta/value.o"
	@echo "... src/objlib/meta/value.i"
	@echo "... src/objlib/meta/value.s"
	@echo "... src/objlib/object.o"
	@echo "... src/objlib/object.i"
	@echo "... src/objlib/object.s"
	@echo "... src/objlib/template.o"
	@echo "... src/objlib/template.i"
	@echo "... src/objlib/template.s"
	@echo "... src/rail/node.o"
	@echo "... src/rail/node.i"
	@echo "... src/rail/node.s"
	@echo "... src/rail/rail.o"
	@echo "... src/rail/rail.i"
	@echo "... src/rail/rail.s"
	@echo "... src/scene/raildata.o"
	@echo "... src/scene/raildata.i"
	@echo "... src/scene/raildata.s"
	@echo "... src/scene/scene.o"
	@echo "... src/scene/scene.i"
	@echo "... src/scene/scene.s"
	@echo "... src/serial.o"
	@echo "... src/serial.i"
	@echo "... src/serial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

